### ISSUE TITLE
small ui detail

### ISSUE THREAD

**Issue by seshubonam** [Pony-House/Client#25]
after you enter a chat on mobile web. looks like the left space could be useful..by  reducinga the gap between the icons and the left edge. a few pixels seem to be wasted on the mobile ui. dont know how it would affect the web ui

**Comment by seshubonam** [comment]
![Screenshot_20230625_031558_Chrome.jpg](https://github.com/Pony-House/Client/assets/1757478/7f3bed63-61a2-4add-90a0-27c7592912b7)

**Comment by seshubonam** [comment]
so that the message occupies a wider space.

**Comment by seshubonam** [comment]
![Screenshot_20230625_032215_Chrome.jpg](https://github.com/Pony-House/Client/assets/1757478/f7b5538f-50f3-4ff2-9693-6b638d54ab57)

****

**Comment by seshubonam** [comment]
original cinny had a wider chat message .. overtime rather than the icon size which gets overlooked subconsiously .. messages need to be more easily viewable, i believe.

**Comment by JasminDreasond** [comment]
The chat of conversation is now a table to make it easier to organize the content on the page. But yes, I will do an analysis of the spacing. Thank you for warning.

**Comment by JasminDreasond** [comment]
I now finished making the adjustments mentioned by you. Feel free to test again.

**Comment by seshubonam** [comment]
looks perfect now🥳 

did you notice this with cinny :

click on a person icon , open a dm and go back... 

and then try to click on home icon. it takes you directly to chat that u last opened in the rooms list. 


same with clicking again on the person icon.. it tales ou to the last dm opened. 


is that intentional?. 

happens on mobile web.

**Comment by seshubonam** [comment]
also sent you a dm on twitter. if you can check. thanks

**Comment by JasminDreasond** [comment]
> looks perfect nowpartying_face
> 
> did you notice this with cinny :
> 
> click on a person icon , open a dm and go back...
> 
> and then try to click on home icon. it takes you directly to chat that u last opened in the rooms list.
> 
> same with clicking again on the person icon.. it tales ou to the last dm opened.
> 
> is that intentional?.
> 
> happens on mobile web.

I now finished solving this problem. Everything is now resolved. I will better analyze your DM tomorrow.
Thank you for everything. ^~^
