### ISSUE TITLE
add something like a (*) to the webpage title when there's unread messages

### ISSUE THREAD

**Issue by ask-compu** [Pony-House/Client#301]
### Describe the problem

i'm color blind and the red dot on the icon can be difficult to see

### Describe the solution you'd like

add a (*) to the page title in addition to the red dot on the icon, and change it to a counter when there's unread pings or DMs

### Alternatives considered

maybe a tampermonkey script?

**Comment by JasminDreasond** [comment]
I worked on something very inspired by Discord in terms of notifications for colorblind people. I avoided using other colors in notifications and also used the same Discord scheme of using custom icons in user statuses.

But before I come to my final conclusion, I want to ask you a question. Is the red color making the icon invisible or are you just having issues to see the icon color?

**Comment by ask-compu** [comment]
> I worked on something very inspired by Discord in terms of notifications for colorblind people. I avoided using other colors in notifications and also used the same Discord scheme of using custom icons in user statuses.
> 
> But before I come to my final conclusion, I want to ask you a question. Is the red color making the icon invisible or are you just having issues to see the icon color?

the red color on the teal background makes it near impossible for me to see, if i really focus on the favicon i can see the red dot but that kinda defeats the point

**Comment by JasminDreasond** [comment]
Okay. I will add the (*) on the page title. I will add this to to-do list.

and I'm going to make a null border like in this image to make it easier to identify the notification icon. I will be inspired by the Slack icon in the image below What do you think of this idea?
![2023-12-05_00-20](https://github.com/Pony-House/Client/assets/24939144/572cbc0b-f70d-4f3b-9897-51cc64fcb19b)

**Comment by ask-compu** [comment]
> Okay. I will add the (*) on the page title. I will add this to to-do list.
> 
> and I'm going to make a null border like in this image to make it easier to identify the notification icon. I will be inspired by the Slack icon in the image below What do you think of this idea? ![2023-12-05_00-20](https://private-user-images.githubusercontent.com/24939144/287907173-572cbc0b-f70d-4f3b-9897-51cc64fcb19b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NDY5MDgsIm5iZiI6MTcwMTc0NjYwOCwicGF0aCI6Ii8yNDkzOTE0NC8yODc5MDcxNzMtNTcyY2JjMGItZjcwZC00ZjNiLTk4OTctNTFjYzY0ZmNiMTliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDAzMjMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlNDZhNDY0ZWQ5ZTY1YjYzOGI4ODIyNTg0Y2E5NDNmNjM4ZDhkNzhhOGE1N2Y1OTZmNzhkOTFhYTFlNzZlMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JMAC0Jz1hPMFLEjBBmd3L7DNdfZJKojH8tgdZFPzOSk)

idk if that will help, if u could do a mockup with the current icon and colors then i would be able to tell u

**Comment by JasminDreasond** [comment]
![2023-12-05_00-46](https://github.com/Pony-House/Client/assets/24939144/dd5d4de8-9de4-4cc7-add1-cc19ff138262)
here :p

**Comment by ask-compu** [comment]
well i had to shrink the image down but i think that does help some, still the (*)/counter in the title would be even more helpful

**Comment by JasminDreasond** [comment]
I sent a update with the requests. I just don't know if all updates are already in the website cache for everyone. If anything is missing, please clear your browser's image cache.

**Comment by ask-compu** [comment]
> I sent a update with the requests. I just don't know if all updates are already in the website cache for everyone. If anything is missing, please clear your browser's image cache.

i noticed the update, but it's a bit off, the counter like (1) should only appear for things like DMs and pings, things that actually make sound and have the counter appear inside the webpage, for other unread messages it should be a (*)
is that possible?

**Comment by JasminDreasond** [comment]
Yep. But first I'll have to do an analysis of how to detect this. I'll let it noted.

**Comment by ask-compu** [comment]
should be just count up the number of messages that engage notifications, u already do this in the webapp itself since DMs and pings will trigger a message counter to appear on the space icon/dm icon, so just take whatever that gets it's counter from
then do the same thing u do now for the icon and page title but if the noisy notification counter is 0 show a (*) instead of of number

**Comment by ask-compu** [comment]
u just gotta count up the number of noisy notifications

**Comment by ask-compu** [comment]
actually this (•) looks better than (*) i think

**Comment by JasminDreasond** [comment]
The numbers in the page title has been resolved and will be added to Friday's update. If this issue has no more new questions, I will close the issue in the Friday. :p
