### ISSUE TITLE
add support for matrix threads

### ISSUE THREAD

**Issue by ask-compu** [Pony-House/Client#302]
### Describe the problem

matrix has thread support since 2022, pony house doesn't seem to support them

### Describe the solution you'd like

add support for threads to pony house

**Comment by JasminDreasond** [comment]
This part of the development is already on the to-do list. It's just not the time yet. I'm currently in the process of adding the "Pin Messages". But I will still keep this issue open so other people know that I will work on it in the future.

**Comment by JasminDreasond** [comment]
This functionality has now been successfully added to the Pony House. I'm closing the issue for now.

**Comment by ask-compu** [comment]
i see the new create thread button but is there a way to show already existing threads?

**Comment by JasminDreasond** [comment]
I forget this part ![fillerwhy](https://github.com/Pony-House/Client/assets/24939144/6486d523-94a9-44fe-b269-9e90acc174cb)
But I will soon do this step after the Christmas.

**Comment by ask-compu** [comment]
no rush, have a merry christmas

**Comment by JasminDreasond** [comment]
tiny complete :3
