### ISSUE TITLE
Dark theme without gradients?

### ISSUE THREAD

**Issue by Sollace** [Pony-House/Client#317]
### Describe the problem

It would be nice to have a version of the dark theme that doesn't have any of those gradient background, or keep the dark theme cinny chat uses as an option.  I find the gradients make it hard to read the text.

### Describe the solution you'd like

.

**Comment by JasminDreasond** [comment]
I will add a new theme option without gradient 😃

**Comment by JasminDreasond** [comment]
all work has been completed. I will close the issue now. Thanks for the tiny request :3
Refresh the page to see new updates. If nothing happens, clear your browser's file cache.

**Comment by Sollace** [comment]
Woohoo! I just noticed it. Thanks!

**Comment by Sollace** [comment]
Oh I just noticed you misspelled gradients though. It says "grandients". Otherwise it works great, @JasminDreasond .

**Comment by JasminDreasond** [comment]
tiny thanks. yep. I'm fixing this now >w<
