### ISSUE TITLE
Global toggle for channel icons

### ISSUE THREAD

**Issue by Sollace** [Pony-House/Client#318]
### Describe the problem

Currently the only person that can turn on and off the channel icons for a space is the owners of that space. I don't really know why that's the case, as it could just be a client option.

### Describe the solution you'd like

I don't really want to go around bugging the owners of every space I'm in to get them to use pony.horse just to make the channel icons visible for their space, so is it possible to make it a client option and maybe add a global toggle to turn it on/off for all spaces instead of specifying for each one?

**Comment by JasminDreasond** [comment]
Noted. I will add this new option soon. :3

**Comment by JasminDreasond** [comment]
I didn't find matrix support for adding **_custom personal settings_** to specific rooms/spaces, but if you find it. Feel free to mention so I can reopen the issue.
