### ISSUE TITLE
make the active space indicator easier to spot at a glance

### ISSUE THREAD

**Issue by ask-compu** [Pony-House/Client#321]
### Describe the problem

the current one looks like this
![image](https://github.com/Pony-House/Client/assets/11810555/661349ae-9956-4218-94d6-7bc56c2c3e4f)
it can be hard to notice at a glance

### Describe the solution you'd like

make the indicator bigger, maybe also change the shape of the icon for the active space

**Comment by ask-compu** [comment]
additionally maybe add an indicator for when there's unread messages in a space that currently has it's icon scrolled off screen

**Comment by ask-compu** [comment]
i want to add that i know there's a change to the background of the currently selected space but that only shows if the icon has transparency, a solution is needed that works regardless of if the icon has transparency

**Comment by Sollace** [comment]
Is this maybe a browser thing? It looks plenty visible on my screen
![image](https://github.com/Pony-House/Client/assets/6429283/cd5bc83d-d780-449e-b2bb-e98099327193)

**Comment by ask-compu** [comment]
idk i'm just using google chrome

**Comment by JasminDreasond** [comment]
There are some visual things that only happen in Firefox or Chrome. I fixed some issues related to this in the past. I will check if this is something that depends on the browser.

**Comment by JasminDreasond** [comment]
Problem fixed. The update is now being deployed via Github Actions.
https://github.com/Pony-House/Client/commit/a86241f456f223d316e3e42f51f66eb26a9550d4

File: src/scss/SidebarAvatar.scss
