### ISSUE TITLE
pressing up arrow key to edit message puts the text cursor at the beginning of the text input

### ISSUE THREAD

**Issue by ask-compu** [Pony-House/Client#324]
### Describe the bug

when pressing the up arrow key the edit message text box puts the cursor at the start instead of the end, basically everything else that supports editing chat messages puts the cursor at the end

also after a sending a message the chat text box is defocused, it refocuses the chat text box when u start to type but if u want to quickly edit a message right after sending it u can't, u have to click the chat text box before the up arrow key will work

### Platform and versions

```shell
OS: Kubuntu 22.04
Browser: Google Chrome 120.0.6099.71
Pony House Version: 1.3.28
Matrix Homeserver: filly.chat
```

**Comment by ask-compu** [comment]
also when sending a message the chat should automatically scroll down to the latest messages if it's been scrolled up, but maybe make that one a settings toggle

**Comment by JasminDreasond** [comment]
I finished. but your second message you will have to open in a new issue.
