### ISSUE TITLE
rendering issue in emoji picker (only in the picker, rendering issue does not exist in actual chat messages)

### ISSUE THREAD

**Issue by ask-compu** [Pony-House/Client#338]
### Describe the bug

![image](https://github.com/Pony-House/Client/assets/11810555/c1c735e3-3a8f-4cfb-800f-0ecfd4c35557)

### Platform and versions

```shell
OS: Kubuntu 22.04
Browser: Google Chrome 120.0.6099.109
Pony House Version: 1.3.28
Matrix Homeserver: filly.chat
```

**Comment by JasminDreasond** [comment]
I'm doing a deploy to fix these issues. Feel free to try.
