### ISSUE TITLE
while editing a message offer the option to delete the message

### ISSUE THREAD

**Issue by ask-compu** [Pony-House/Client#351]
### Describe the problem

on most other chat platforms when you edit a message, remove all the text from it, and hit enter/save it offers to delete the message

### Describe the solution you'd like

add a dialog asking to delete the message if you edit a message and remove all the text from it, allow confirming this dialog with a 2nd press of the enter key

**Comment by JasminDreasond** [comment]
Feature added here: [edit message - empty edit is to delete message ](https://github.com/Pony-House/Client/commit/80387054de09184b330861e6ea66045aef8d7750)
When the deployment is finished, everything will be available for use.
