### ISSUE TITLE
App Crashes when pressing Maximize button

### ISSUE THREAD

**Issue by maemoe** [Pony-House/Client#557]
### Describe the bug

The Pony House Client Crashes when I attempt to Maximize it with the following exit error : 

```
[mae@moe linux-unpacked]$ ./pony-house-matrix
Segmentation fault (core dumped)
```

```
[mae@moe pony-house-matrix-appimage]$ ./Pony.House-1.3.45.AppImage 
Segmentation fault (core dumped)
```

Tested both on Wayland and X11 with same results

### Reproduction

1. Open the Appimage or Extracted Linux Package
2. Run the Application
3. Press Maximize

### Expected behavior

For the app to Maximize and not Crash

### Platform and versions

```shell
1. OS : Archlinux
2. Kernel : 6.9.1-arch1-2
3. Platform x86_64 (ThinkPad L580)
4. Desktop Environment : Gnome 46.1 Wayland
5. Pony House Version : 1.3.45
```

### Additional context

Not too sure on how to do debugging, feedback on how I can do so very welcomed 👍️

**Comment by JasminDreasond** [comment]
that was corrected last week. i'm just late to release the version. but don't worry that i'll do it today.
