### ISSUE TITLE
Clicking pinned icon on Windows taskbar does not open Pony House

### ISSUE THREAD

**Issue by ryderryderryd** [Pony-House/Client#689]
### Describe the bug

When pinning Pony House to the taskbar on Windows, clicking on the icon does not open Pony House. The only way to open Pony House after closing it is by using the tray icon.
![2024-08-1104-17-24-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/4a746cfa-8dc7-4514-a6ec-e9b6d186b43a)

### Reproduction

1. Open Pony House
2. Pin it to the taskbar
3. Close it
4. Click the pinned icon

### Expected behavior

Pony House opens when clicking the pinned icon.

### Platform and versions

```shell
1. OS: Windows 11
2. Browser: N/A (Using desktop version)
3. Version: v1.4.5
4: Homeserver: amber.tel
```

**Comment by JasminDreasond** [comment]
I will solve this issue after solving the https://github.com/Pony-House/Client/issues/683
More information: https://github.com/Pony-House/Client/issues/683#issuecomment-2292753181

**Comment by JasminDreasond** [comment]
I hope the issue was solved for you. It is now working here.
https://github.com/Pony-House/Client/releases/tag/1.4.8

**Comment by ryderryderryd** [comment]
Can confirm it works now, thank you so much!
